export const PONY_NAMES: readonly (readonly [name: string, tag: string])[] = [
  ['Twilight Sparkle', 'twilight sparkle'],
  ['Fluttershy', 'fluttershy'],
  ['Rainbow Dash', 'rainbow dash'],
  ['Pinkie Pie', 'pinkie pie'],
  ['Rarity', 'rarity'],
  ['Princess Luna', 'princess luna'],
  ['Applejack', 'applejack'],
  ['Princess Celestia', 'princess celestia'],
  ['Sunset Shimmer', 'sunset shimmer'],
  ['Trixie', 'trixie'],
  ['Derpy Hooves', 'derpy hooves'],
  ['Starlight Glimmer', 'starlight glimmer'],
  ['Queen Chrysalis', 'queen chrysalis'],
  ['Princess Cadance', 'princess cadance'],
  ['DJ Pon-3', 'dj pon-3'],
  ['Vinyl Scratch', 'vinyl scratch'],
  ['Octavia Melody', 'octavia melody'],
  ['Lyra Heartstrings', 'lyra heartstrings'],
]
