server {
    listen 80;
    server_name _;

    location / {
        auth_basic "Stream";
        auth_basic_user_file /auth/.htpasswd;

        proxy_pass http://discordmtx:8889;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
